spring:
  application:
    name: food
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FoodStore;encrypt=false
    username: sa
    password: FoodStore@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8088